/// Flutter icons Tmdb
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tmdb
///      fonts:
///       - asset: fonts/Tmdb.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Tmdb {
  Tmdb._();

  static const _kFontFam = 'Tmdb';
  static const String _kFontPkg = null;

  static const IconData music = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
